
[General]
	#The message which will be sent to players when they use the /vote command.
	voteCommandMessage = "Thank You It Really Helps. https://minecraftservers.org/server/604787 https://minecraft-server-list.com/server/472552/ https://www.planetminecraft.com/server/tnp-limitless-lite-semi-official-server/ https://minecraft-mp.com/server-s278193"

